export const DETECT_FACE_REQUEST = "DETECT_FACE_REQUEST";
export const DETECT_FACE_SUCCESS = "DETECT_FACE_SUCCESS";
export const DETECT_FACE_FAIL = "DETECT_FACE_FAIL";

export const CLEAR_ERRORS = "CLEAR_ERRORS";
